sudo: required
language: perl
perl:
  - "5.18"
  - "5.20"
  - "5.22"

env:
  global:
    - PERL_MM_USE_DEFAULT=1
    - "PATH=$PATH:$TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR/hap1.2:/opt/ngs-tools/bin:$TRAVIS_BUILD_DIR/gfe_submission/bin"
    - NXF_VER='0.22.4'
    - NXF_OPTS='-Xms512M -Xmx2G'

before_install:
  - sudo apt-get install -qyy openjdk-7-jre-headless perl-doc wget curl build-essential git libssl-dev
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
  - cp docker/hap1.2.tar.gz docker/ngs-tools_1.9.deb .
  - sudo dpkg --install ngs-tools_1.9.deb
  - curl -fsSL get.nextflow.io | bash
  - tar -xvzf hap1.2.tar.gz
  - chmod a+x hap1.2/hap1.2.jar
  - wget http://www.clustal.org/omega/clustalo-1.2.3-Ubuntu-x86_64
  - mv clustalo-1.2.3-Ubuntu-x86_64 hap1.2/clustalo
  - chmod a+x hap1.2/clustalo
  - cd GFE_Submission
  - cpanm --quiet --notest Test::More@1.302075
  - cpanm --quiet --notest YAML@1.21
  - cpanm --quiet --notest Moose@2.2004
  - cpanm --quiet --notest Dancer@1.3202
  - cpanm --quiet --notest JSON@2.90
  - cpanm --quiet --notest Dancer::Plugin::Swagger@0.2.0
  - cpanm --quiet --notest Log::Log4perl@1.48
  - cpanm --quiet --notest JSON::Schema::AsType@0.1.0
  - cpanm --quiet --notest Plack::Handler::Starman
  - cpanm --quiet --notest Plack@1.0042
  - cpanm --quiet --notest Template@2.26
  - cpanm --quiet --notest Getopt::Long@1.3142
  - cpanm --quiet --notest LWP::UserAgent@6.17
  - cpanm --quiet --notest Dancer::Plugin::Swagger@0.2.0
  - cpanm --quiet --notest Net::SSLeay@1.58
  - cpanm --quiet --notest JSON::Schema::AsType@0.1.0
  - cpanm --quiet --notest IO::Socket::SSL@2.044
  - cpanm --quiet --notest REST::Client@273
  - cpanm --quiet --notest Math::Round@0.07
  - cpanm --quiet --notest File::Spec@3.40
  - cpanm --quiet --notest XML::DOM@1.46
  - cpanm --quiet --notest Try::Tiny@0.28
  - cpanm --quiet --notest --skip-satisfied --installdeps .
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cd ..
  - mv -i GFE_Submission gfe_submission
  - cd gfe_submission

script:
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
    - cover

after_success:
    - cover -report coveralls
