sudo: required
dist: trusty

env:
  global:
    - PERL_MM_USE_DEFAULT=1

before_install:
  - sudo apt-get install -qyy openjdk-7-jre-headless perl-doc wget curl build-essential git libssl-dev
  - cp docker/hap1.1.tar.gz .
  - tar -xvzf hap1.1.tar.gz
  - chmod a+x hap1.1/hap1.1.jar
  - wget http://www.clustal.org/omega/clustalo-1.2.3-Ubuntu-x86_64
  - mv clustalo-1.2.3-Ubuntu-x86_64 hap1.1/clustalo
  - chmod a+x hap1.1/clustalo
  - sudo cpan YAML Plack Plack::Handler::Starman Template JSON Getopt::Long Data::Dumper LWP::UserAgent REST::Client Test::More Dancer
  - sudo cpan JSON::Schema::AsType Moose Math::Round File::Spec IO::Socket::SSL Net::SSLeay Dancer::Plugin::Swagger Log::Log4perl

script: "./build.sh"
